// Bariable global base URL para las peticiones local...
let baserUrl = "http://localhost:8191";

// Bariable global base URL para las peticiones Remoto para la fase de test...
// let baserUrl = "http://mrjob22.herokuapp.com"; --> mrjob22.herokuapp.com/student/getAll
export default baserUrl;
